### ISSUE TITLE
Wrong keyboard on mobile devices

### ISSUE THREAD

**Issue by mikmikmik** [uhlryk/angular-dynamic-number#14]
It would be preferable to have a numeric keyboard when you type in a numeric field but it is not the case with using this plugin because it needs a type="text".
I tried to add a numeric pattern like [0-9\s]\* or [\d\s]\* but it didn't work. I tried inputmode="numeric" but it didn't work.
I know type="number" is problematic with using other chars than numbers so I tried with type="tel" which is a known workaround and it worked well after adding the [type="tel" as an alternative on L453](https://github.com/uhlryk/angular-dynamic-number/blob/master/src/numberDirective.js#L453).
I use the plugin mainly for controlling the number of digits and adding thousand separators.
Do you know if it could cause issues? Do you have an alternative solution if it's the case?

Cheers

**Comment by uhlryk** [comment]
I know about inconsistency of number field - different browsers give different output. Therefore I forced to use string as most safe input type.
Phone number could work. Im not sure about it in 100% for all browsers. But I thing that number of pros is greater then cons (this field gives better keyboard and it is easy to change to type text id there are problems with this). 
We will allow to use phone input (I will merge your pull request), but I have some small issues. I will write it as code review in your pull request (please check it).

**Comment by uhlryk** [comment]
I merged your pull request. Thanks for great job
