### ISSUE TITLE
Incorrect formatting when using European number format

### ISSUE THREAD

**Issue by 3thanZ** [uhlryk/angular-dynamic-number#16]
@uhlryk  In many European countries, the thousands separator is `.` and the fraction separator is `,`. There is a bug in version 1.9.2 where values `0.1234` is displayed as `0,1.234`. This is because the fraction separator in the function `addThousandSeparator` is hardcoded to `.`. Instead it should be an argument passed in from other calling functions.

**Comment by uhlryk** [comment]
thanks, you have right. I fixed it. Changes are available in v1.9.3
