### ISSUE TITLE
Entering a non-numeric character as the first character in an empty input field parses and displays as "null".

### ISSUE THREAD

**Issue by 3thanZ** [uhlryk/angular-dynamic-number#17]
If I enter a non numerical value in an input field monitored by angular-dynamic-number, the line that calls `convModelToView` returns the string "null". This happens only when the page is first loaded.

```
if(viewRegexTest.test(parsedValue) === false){
      var modelValue = convModelToView(ngModelController.$modelValue, fractionSeparator, prepend, append);
      if(isThousandSeparator){
        modelValue = addThousandSeparator(modelValue, fractionSeparator, thousandSeparator);
      }
      changeViewValue(ngModelController, modelValue, prepend, append);
      setCaretPosition(element[0],cursorPosition-1);
      return ngModelController.$modelValue;
    }
```

Once I get "null" being displayed in the input field and when I clear the field and enter another non numerical character, the behavior works correctly then, and rejects the non numerical character. I noticed that this is because modelValue is `undefined` the second time around, whereas in the first instance, it was null.

```
function convModelToView(modelValue, viewSeparator, prepend, append){
    if(modelValue === undefined) {
      return '';
    }
    var newViewValue = '';
    if(viewSeparator === ',') {
      newViewValue = String(modelValue).replace(".",",");
    } else {
      newViewValue = String(modelValue);
    }
    return addPrependAppend(newViewValue, prepend, append);
  }
```

Can I propose that the line `if(modelValue === undefined)` can be modified to also capture `null`?

**Comment by uhlryk** [comment]
> Can I propose

Any help is always welcome. Thank you very much.
I made changes based on your proposal, please check if now it works correctly - it is v1.9.4.

**Comment by 3thanZ** [comment]
Thanks Krzysztof

On Monday, 6 June 2016, Krzysztof Sztompka notifications@github.com wrote:

> Can I propose
> 
> Any help is always welcome. Thank you very much.
> I made changes based on your proposal, please check if now it works
> correctly - it is v1.9.4.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/uhlryk/angular-dynamic-number/issues/17#issuecomment-223836639,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABZoiDrQ7e76n1kfYG6NgVe1YMeYzep8ks5qIzXNgaJpZM4IuKHu
> .

## 

Best regards,
Ethan Siew
Mobile: +6012 3822 032
