### ISSUE TITLE
Working with objects

### ISSUE THREAD

**Issue by elieobeid7** [uhlryk/angular-dynamic-number#28]
Do you have any example on how to format objects using this library?

**Comment by uhlryk** [comment]
Yes. please check http://htmlpreview.github.io/?https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html
and at the bottom there are section "Example of angular dynamic number filter"
It begins from this line https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html#L159

**Comment by elieobeid7** [comment]
will take a look and let you know thanks!

**Comment by elieobeid7** [comment]
Issue solved, you may close the ticket, thanks for your help
