### ISSUE TITLE
Input cursor position incorrect after typing intial period character

### ISSUE THREAD

**Issue by freedomflyer** [uhlryk/angular-dynamic-number#29]
See http://recordit.co/oAMcve3pUY

Instead of typing "0.5" into the textbox, I attempted to type ".5" without the leading 0. This sets an incorrect cursor location. @uhlryk any ideas?

**Comment by uhlryk** [comment]
Thank you for your feedback.
Typing only separator char hasn't been supported. But it looks interesting (it is hard to cover all user habits), therefore now it should work correctly (v1.12.4).

Please try it (in example page http://htmlpreview.github.io/?https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html you could check first and second input).
