### ISSUE TITLE
Minification error: not using explicit annotation

### ISSUE THREAD

**Issue by cfragout** [uhlryk/angular-dynamic-number#36]
Hi! I found the following error when trying to use the plugin (v 2.1.0) in my app (minified):
Error: [$injector:strictdi] function(t) is not using explicit annotation and cannot be invoked in strict mode

In order to fix this, I've just changed line 644 to look as follows:
`.filter('awnum', ['dynamicNumberStrategy', function(dynamicNumberStrategy) {`
(curly braket closes in line 668).

If you could fix this in any upcoming version, that would be awesome.

Thanks!

**Comment by uhlryk** [comment]
Thanks,
I added your change.
