### ISSUE TITLE
Custom strategy doesn't works

### ISSUE THREAD

**Issue by gglazer** [uhlryk/angular-dynamic-number#4]
Hi All,

the custom strategy doesn't works.
I've created a sample Plunkr: https://plnkr.co/edit/XUcDI9KkM67BuThmnX2Z?p=preview
So I've copied this custom lines from your example code.
If I change the 'numNeg' property to 'false' in my 'price' strategy, the result page won't works properly (it allows the negative numbers)...

**Comment by uhlryk** [comment]
Hi
Thank you very much for your ticket. Yes there was problem with strategies.
I hope I fixed it.
Please check this again. I forked and update your plunker : https://plnkr.co/edit/nRJxYNckJGgF7T7W9m7S?p=preview

**Comment by gglazer** [comment]
Hi
It works!
When will you fix this in the real code?

**Comment by uhlryk** [comment]
I fixed it :)
It is v1.5.5
