### ISSUE TITLE
When user types minus model assumes 0

### ISSUE THREAD

**Issue by leonardobh** [uhlryk/angular-dynamic-number#46]
If user types minus on an input that accepts so, model is automatically assigned zero, what causes the field to be valid even tough it only shows a minus character on the screen. Shouldn't only minus keep model undefined, so it would be invalid for instance?

It looks like directiveParser (line 349) returns zero even if its only a minus symbol.

**Comment by uhlryk** [comment]
I will consider this. I think you have a right. If so I will change it as soon as possible.

**Comment by uhlryk** [comment]
It will be fixed. Now it is on branch `return-null`. After few days if everything working as expected I will merge it to master. (If you wish check it/test it/use it you can update your installation to use branch)

**Comment by marco24690** [comment]
Still not working for me.
Typing only minus symbol in a required input make the field valid

Version 2.5.1
