### ISSUE TITLE
ViewValue changes to 0 when the input field is invalid and try to exceed max digits defined by num-int. 

### ISSUE THREAD

**Issue by FloatingShepherd** [uhlryk/angular-dynamic-number#49]
Hi uhlryk, 

I have one input field which $invalid === true. I also set max digits to 9 by using num-int. When I tried to type the 10th character, the viewValue of the field changed to 0. I understood that the modelValue was cleared to 0 when the field became invalid. But I think we probably do not want to clear viewValue in this case. 

Besides of that the module worked perfectly for me :)

Thanks,

Qing

**Comment by uhlryk** [comment]
Thank you for your feedback. It shouldn't change to 0. Something is wrong I will check it. It should only happen if you try paste value which has wrong size then it will replace it with 0.

**Comment by tamvm** [comment]
I found same problem with this issue. Have you had a chance to check and fix it yet? 

Thanks

**Comment by uhlryk** [comment]
hey it should be fixed in latest version. Please check it.
