### ISSUE TITLE
Thousand separator 

### ISSUE THREAD

**Issue by manuelagard** [uhlryk/angular-dynamic-number#5]
Very good directive. However, it would be great to be able to configure the separator character, because many European countries use a space instead of a comma.

**Comment by uhlryk** [comment]
Thanks.
It looks simple. I will check this.

**Comment by gglazer** [comment]
+1

**Comment by uhlryk** [comment]
I added this functionality.
You can check it in [demo](http://htmlpreview.github.io/?https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html) in fourth input.
Please test it, because this directive have huge number of combinations, and I could miss something.

**Comment by manuelagard** [comment]
Great job ! 
it works perfectly...
Thanks !
