### ISSUE TITLE
Input append and prepend

### ISSUE THREAD

**Issue by manuelagard** [uhlryk/angular-dynamic-number#6]
Hi,

I think it could be really useful to add 2 options to specify a string that could be placed before and/or after the input value.
For instance : 
num-prepend: "$"   ==> would add the "$" just before the value : $100,000
num-append: "€" ==> would add the "€" just after the value : 100,000€

What o you think ? I think that could make this directive with wide possibilities !

**Comment by uhlryk** [comment]
I like it. It should be quite easy.

**Comment by uhlryk** [comment]
@manuelagard how negative number should look like with num-prepend?
1. -$100,000
2. $-100,000

or maybe when we have num-prepend we should disallow negative numbers?

Logically it should be $-100,000, but maybe it is not correct number (I'm not native speaker)

**Comment by manuelagard** [comment]
@uhlryk great to see that it goes forward !
I really like your plugin : very light and easy to use...
For negative number, I would say option 1 is the right one.
In any case, I used this option (n°1) in one of my app for many customers and I did not have any request or comment regarding this notation from them.
So I vote for option 1 !

**Comment by uhlryk** [comment]
Thank you for your kind words. Im very glad that this plugin is usable.

I have added this functionality.
It is v1.7.0
You can check it in demo page ([link](http://htmlpreview.github.io/?https://github.com/uhlryk/angular-dynamic-number/blob/master/examples/index.html)) - ninth and tenth input. 

when you find any problems with this functionality or other please open new ticket. I found one little problem #7
